package VIEW;

import java.io.IOException;
import javax.swing.JOptionPane;

//import DAL.ConexaoBD;           //Conexao remota
import java.sql.*;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

import DAO.ConnectionControler;

import java.awt.event.KeyEvent;
import java.awt.event.ActionEvent;
import java.awt.event.InputEvent;
import javax.swing.ImageIcon;
import java.awt.Font;
import java.awt.Insets;
import java.awt.Component;
import javax.swing.UIManager;
import javax.swing.JMenuBar;
import javax.swing.JFrame;

public class Principal extends javax.swing.JFrame {

    Connection conexao = null;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JdpPrincipal = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();
        JMenuBar menu = new javax.swing.JMenuBar();
        menu.setMargin(new Insets(5, 5, 5, 5));
        menu.setFont(new Font("Arial", Font.PLAIN, 14));
        menuFuncionarios = new javax.swing.JMenu();
        menuFuncionarios.setFont(new Font("Arial", Font.PLAIN, 14));
        menuFuncionarios.setSelectedIcon(new ImageIcon(Principal.class.getResource("/VIEW/IMG/ico_funcionario.png")));
        menuFuncionarios.setIcon(new ImageIcon(Principal.class.getResource("/VIEW/IMG/ico_funcionario.png")));
        MenuItemAbrir = new javax.swing.JMenuItem();
        MenuItemAbrir.setFont(new Font("Arial", Font.PLAIN, 14));

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setTitle("SISRH");
        setLocation(new java.awt.Point(0, 0));

        JdpPrincipal.setPreferredSize(new java.awt.Dimension(900, 800));

        jLabel1.setIcon(new ImageIcon(Principal.class.getResource("/VIEW/IMG/tela_principal_bg.png"))); // NOI18N
        jLabel1.setToolTipText("");

        JdpPrincipal.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JdpPrincipalLayout = new javax.swing.GroupLayout(JdpPrincipal);
        JdpPrincipal.setLayout(JdpPrincipalLayout);
        JdpPrincipalLayout.setHorizontalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JdpPrincipalLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 900, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        JdpPrincipalLayout.setVerticalGroup(
            JdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
        );

        menuFuncionarios.setText("Quadro Pessoal");
        menuFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	menuFuncionariosActionPerformed(evt);
            }
        });

        MenuItemAbrir.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F, InputEvent.CTRL_DOWN_MASK | InputEvent.ALT_DOWN_MASK));
        MenuItemAbrir.setText("Funcionários");
        MenuItemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemAbrirActionPerformed(evt);
            }
        });
        menuFuncionarios.add(MenuItemAbrir);

        menu.add(menuFuncionarios);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    protected void menuFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO Auto-generated method stub
	}

    private void MenuItemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemAbrirActionPerformed
        TelaFuncionario carregar = new TelaFuncionario();
        JdpPrincipal.add(carregar);

        carregar.setVisible(true);


    }//GEN-LAST:event_MenuItemAbrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    private javax.swing.JDesktopPane JdpPrincipal;
    private javax.swing.JMenuItem MenuItemAbrir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu menuFuncionarios;
    // End of variables declaration//GEN-END:variables
    
    
    
    
    
    
}